"""Application ports: stable boundaries between the core and infrastructure."""

from __future__ import annotations

from typing import Protocol

from .domain import DiscoveryTask, Evidence, Finding, FindingFeedback, KnowledgeRecord, Source


class DiscoveryRepository(Protocol):
    """Persistence boundary used by application services."""

    def save_task(self, task: DiscoveryTask) -> None: ...
    def get_task(self, task_id: str) -> DiscoveryTask | None: ...
    def save_source(self, source: Source) -> None: ...
    def list_sources(self, task_id: str) -> list[Source]: ...
    def save_evidence(self, evidence: Evidence) -> None: ...
    def list_evidence(self, task_id: str) -> list[Evidence]: ...
    def save_finding(self, finding: Finding) -> None: ...
    def list_findings(self, task_id: str) -> list[Finding]: ...
    def save_feedback(self, feedback: FindingFeedback) -> None: ...
    def list_feedback(self, task_id: str) -> list[FindingFeedback]: ...
    def save_knowledge(self, record: KnowledgeRecord) -> None: ...
    def list_knowledge(self) -> list[KnowledgeRecord]: ...
